export const data = [
    {
      name: "India",
      population: "125 Crores",
      males: "50 Crores",
      females: "75 Crores",
      average_age: "27",
      states: [
        {
          name: "Maharashtra",
          population: "12 Crores",
          males: "5 Crores",
          test: 124,
        },
        {
          name: "Uttar Pradesh",
          females: "10 Crores",
          average_age: "26",
        },
        {
          name: "Karnataka",
          population: "6 Crores",
          males: "3 Crores",
          females: "3 Crores",
          average_age: "30",
        },
      ],
    },
    {
      name: "United States",
      population: "330 Million",
      males: "160 Million",
      females: "170 Million",
      average_age: "35",
      states: [
        {
          name: "California",
          population: "39 Million",
          males: "19 Million",
          females: "20 Million",
          average_age: "33",
        },
        {
          name: "Texas",
          population: "29 Million",
          males: "15 Million",
          females: "14 Million",
          average_age: "36",
        },
        {
          name: "New York",
          population: "20 Million",
          males: "9 Million",
          females: "11 Million",
          average_age: "32",
        },
      ],
    },
    {
      name: "China",
      population: "140 Crores",
      males: "70 Crores",
      females: "70 Crores",
      average_age: "32",
      states: [
        {
          name: "Guangdong",
          population: "11 Crores",
          males: "5 Crores",
          females: "6 Crores",
          average_age: "31",
        },
        {
          name: "Jiangsu",
          population: "8 Crores",
          males: "4 Crores",
          females: "4 Crores",
          average_age: "33",
        },
        {
          name: "Guangdong",
          population: "11 Crores",
          males: "5 Crores",
          females: "6 Crores",
          average_age: "31",
        },
        {
          name: "Jiangsu",
          population: "8 Crores",
          males: "4 Crores",
          females: "4 Crores",
          average_age: "33",
        },
      ],
    },
    {
      name: "new",
      population: "140 Crores",
      males: "70 Crores",
      females: "70 Crores",
      average_age: "32",
      states: [],
    },
  ];